version: "3"
services:

  flask:
    build:
      context: ./
    image: flask-digest
    ports:
      - "5000:5000"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
